/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UserProfile {
    staffId?: string;
    name: string;
    role: string;
}
export interface Treatment {
    date: Time;
    plan?: TreatmentPlan;
    type: string;
    notes: string;
    price: bigint;
}
export interface Location {
    latitude: number;
    longitude: number;
    timestamp: Time;
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Spending {
    id: string;
    date: Time;
    description: string;
    category: SpendingCategory;
    amount: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface PatientSession {
    id: string;
    checkIn: Time;
    duration: bigint;
    visitNumber: bigint;
    progressPercentage: bigint;
    patientId: string;
    date: Time;
    treatmentPackageId: string;
    checkOut?: Time;
}
export interface MiscExpense {
    id: string;
    date: Time;
    description: string;
    category: SpendingCategory;
    amount: bigint;
}
export interface Patient {
    id: string;
    debt: bigint;
    name: string;
    paid: bigint;
    diagnosis: string;
    address: string;
    phone: string;
    treatments: Array<Treatment>;
}
export interface CheckOutData {
    patientId: string;
}
export interface StaffMember {
    id: string;
    name: string;
    qualifications: string;
    phone: string;
    position: string;
    payRate: bigint;
}
export interface TreatmentPlan {
    endDate: Time;
    description: string;
    startDate: Time;
}
export interface StaffAttendance {
    id: string;
    staffId: string;
    date: Time;
    hoursWorked: bigint;
    clockOut?: Time;
    clockIn: Time;
    totalPay: bigint;
    locationHistory: Array<Location>;
    payRate: bigint;
    location?: Location;
}
export interface ClockInData {
    staffId: string;
    location?: Location;
}
export interface BackupRecord {
    id: string;
    timestamp: Time;
    recordCount: {
        spendings: bigint;
        attendances: bigint;
        staff: bigint;
        sessions: bigint;
        patients: bigint;
        miscExpenses: bigint;
    };
}
export interface CheckInData {
    visitNumber: bigint;
    patientId: string;
    treatmentPackageId: string;
}
export interface BackupData {
    spendings: Array<Spending>;
    attendances: Array<StaffAttendance>;
    staff: Array<StaffMember>;
    sessions: Array<PatientSession>;
    timestamp: Time;
    patients: Array<Patient>;
    miscExpenses: Array<MiscExpense>;
}
export interface ClockOutData {
    staffId: string;
}
export interface EditableSessionFields {
    checkIn?: Time;
    duration?: bigint;
    visitNumber?: bigint;
    progressPercentage?: bigint;
    patientId?: string;
    date?: Time;
    treatmentPackageId?: string;
    checkOut?: Time;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum SpendingCategory {
    equipment = "equipment",
    marketing = "marketing",
    supplies = "supplies",
    misc = "misc",
    rent = "rent",
    utilities = "utilities",
    insurance = "insurance",
    medications = "medications"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    addMiscExpense(expense: MiscExpense): Promise<void>;
    addPatient(patient: Patient): Promise<void>;
    addSpending(spending: Spending): Promise<void>;
    addStaff(staffMember: StaffMember): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    checkInPatient(data: CheckInData): Promise<void>;
    checkOutPatient(data: CheckOutData): Promise<void>;
    clockInStaff(data: ClockInData): Promise<void>;
    clockOutStaff(data: ClockOutData): Promise<void>;
    createBackupRecord(data: BackupData, recordId: string): Promise<void>;
    deleteMiscExpense(id: string): Promise<void>;
    deletePatient(id: string): Promise<void>;
    deleteStaff(id: string): Promise<void>;
    editCheckInTime(patientId: string, sessionId: string, newCheckInTime: Time): Promise<void>;
    editCheckOutTime(patientId: string, sessionId: string, newCheckOutTime: Time): Promise<void>;
    editClockInTime(staffId: string, attendanceId: string, newClockInTime: Time): Promise<void>;
    editClockOutTime(staffId: string, attendanceId: string, newClockOutTime: Time): Promise<void>;
    editSpending(id: string, updatedSpending: Spending): Promise<void>;
    exportAllData(): Promise<BackupData>;
    getAllAttendances(): Promise<Array<StaffAttendance>>;
    getAllMiscExpenses(): Promise<Array<MiscExpense>>;
    getAllPatients(): Promise<Array<Patient>>;
    getAllSessions(): Promise<Array<PatientSession>>;
    getAllSpendings(): Promise<Array<Spending>>;
    getAllStaff(): Promise<Array<StaffMember>>;
    getBackupRecords(): Promise<Array<BackupRecord>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getPatientSessions(patientId: string): Promise<Array<PatientSession>>;
    getSpendingsByCategory(category: SpendingCategory): Promise<Array<Spending>>;
    getStaffAttendance(staffId: string): Promise<Array<StaffAttendance>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    importBackupData(backupData: BackupData): Promise<void>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    mergeBackupData(backupData: BackupData): Promise<void>;
    resetAllData(): Promise<void>;
    resetAllPatients(): Promise<void>;
    resetAllStaff(): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateMiscExpense(id: string, expense: MiscExpense): Promise<void>;
    updatePatient(id: string, patient: Patient): Promise<void>;
    updatePatientSession(id: string, changes: EditableSessionFields): Promise<void>;
    updateStaff(id: string, staffMember: StaffMember): Promise<void>;
    updateStaffLocation(staffId: string, location: Location): Promise<void>;
}
import type { BackupData as _BackupData, ClockInData as _ClockInData, EditableSessionFields as _EditableSessionFields, Location as _Location, MiscExpense as _MiscExpense, Patient as _Patient, PatientSession as _PatientSession, Spending as _Spending, SpendingCategory as _SpendingCategory, StaffAttendance as _StaffAttendance, StaffMember as _StaffMember, Time as _Time, Treatment as _Treatment, TreatmentPlan as _TreatmentPlan, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async addMiscExpense(arg0: MiscExpense): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMiscExpense(to_candid_MiscExpense_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMiscExpense(to_candid_MiscExpense_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addPatient(arg0: Patient): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPatient(to_candid_Patient_n12(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPatient(to_candid_Patient_n12(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addSpending(arg0: Spending): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addSpending(to_candid_Spending_n17(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSpending(to_candid_Spending_n17(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addStaff(arg0: StaffMember): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addStaff(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addStaff(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n18(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n18(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async checkInPatient(arg0: CheckInData): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.checkInPatient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkInPatient(arg0);
            return result;
        }
    }
    async checkOutPatient(arg0: CheckOutData): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.checkOutPatient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkOutPatient(arg0);
            return result;
        }
    }
    async clockInStaff(arg0: ClockInData): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clockInStaff(to_candid_ClockInData_n20(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clockInStaff(to_candid_ClockInData_n20(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async clockOutStaff(arg0: ClockOutData): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clockOutStaff(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clockOutStaff(arg0);
            return result;
        }
    }
    async createBackupRecord(arg0: BackupData, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createBackupRecord(to_candid_BackupData_n22(this._uploadFile, this._downloadFile, arg0), arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBackupRecord(to_candid_BackupData_n22(this._uploadFile, this._downloadFile, arg0), arg1);
            return result;
        }
    }
    async deleteMiscExpense(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMiscExpense(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMiscExpense(arg0);
            return result;
        }
    }
    async deletePatient(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePatient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePatient(arg0);
            return result;
        }
    }
    async deleteStaff(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStaff(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStaff(arg0);
            return result;
        }
    }
    async editCheckInTime(arg0: string, arg1: string, arg2: Time): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editCheckInTime(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editCheckInTime(arg0, arg1, arg2);
            return result;
        }
    }
    async editCheckOutTime(arg0: string, arg1: string, arg2: Time): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editCheckOutTime(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editCheckOutTime(arg0, arg1, arg2);
            return result;
        }
    }
    async editClockInTime(arg0: string, arg1: string, arg2: Time): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editClockInTime(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editClockInTime(arg0, arg1, arg2);
            return result;
        }
    }
    async editClockOutTime(arg0: string, arg1: string, arg2: Time): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editClockOutTime(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editClockOutTime(arg0, arg1, arg2);
            return result;
        }
    }
    async editSpending(arg0: string, arg1: Spending): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editSpending(arg0, to_candid_Spending_n17(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editSpending(arg0, to_candid_Spending_n17(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async exportAllData(): Promise<BackupData> {
        if (this.processError) {
            try {
                const result = await this.actor.exportAllData();
                return from_candid_BackupData_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.exportAllData();
            return from_candid_BackupData_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllAttendances(): Promise<Array<StaffAttendance>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAttendances();
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAttendances();
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllMiscExpenses(): Promise<Array<MiscExpense>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMiscExpenses();
                return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMiscExpenses();
            return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPatients(): Promise<Array<Patient>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPatients();
                return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPatients();
            return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllSessions(): Promise<Array<PatientSession>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSessions();
                return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSessions();
            return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllSpendings(): Promise<Array<Spending>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSpendings();
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSpendings();
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllStaff(): Promise<Array<StaffMember>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStaff();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStaff();
            return result;
        }
    }
    async getBackupRecords(): Promise<Array<BackupRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBackupRecords();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBackupRecords();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n61(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n61(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPatientSessions(arg0: string): Promise<Array<PatientSession>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPatientSessions(arg0);
                return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPatientSessions(arg0);
            return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSpendingsByCategory(arg0: SpendingCategory): Promise<Array<Spending>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSpendingsByCategory(to_candid_SpendingCategory_n10(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSpendingsByCategory(to_candid_SpendingCategory_n10(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStaffAttendance(arg0: string): Promise<Array<StaffAttendance>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStaffAttendance(arg0);
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStaffAttendance(arg0);
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async importBackupData(arg0: BackupData): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.importBackupData(to_candid_BackupData_n22(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.importBackupData(to_candid_BackupData_n22(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async mergeBackupData(arg0: BackupData): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.mergeBackupData(to_candid_BackupData_n22(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.mergeBackupData(to_candid_BackupData_n22(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async resetAllData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetAllData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetAllData();
            return result;
        }
    }
    async resetAllPatients(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetAllPatients();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetAllPatients();
            return result;
        }
    }
    async resetAllStaff(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetAllStaff();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetAllStaff();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n63(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n63(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateMiscExpense(arg0: string, arg1: MiscExpense): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMiscExpense(arg0, to_candid_MiscExpense_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMiscExpense(arg0, to_candid_MiscExpense_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updatePatient(arg0: string, arg1: Patient): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePatient(arg0, to_candid_Patient_n12(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePatient(arg0, to_candid_Patient_n12(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updatePatientSession(arg0: string, arg1: EditableSessionFields): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePatientSession(arg0, to_candid_EditableSessionFields_n65(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePatientSession(arg0, to_candid_EditableSessionFields_n65(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateStaff(arg0: string, arg1: StaffMember): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStaff(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStaff(arg0, arg1);
            return result;
        }
    }
    async updateStaffLocation(arg0: string, arg1: Location): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStaffLocation(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStaffLocation(arg0, arg1);
            return result;
        }
    }
}
function from_candid_BackupData_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BackupData): BackupData {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_MiscExpense_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MiscExpense): MiscExpense {
    return from_candid_record_n37(_uploadFile, _downloadFile, value);
}
function from_candid_PatientSession_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PatientSession): PatientSession {
    return from_candid_record_n47(_uploadFile, _downloadFile, value);
}
function from_candid_Patient_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Patient): Patient {
    return from_candid_record_n50(_uploadFile, _downloadFile, value);
}
function from_candid_SpendingCategory_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SpendingCategory): SpendingCategory {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid_Spending_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Spending): Spending {
    return from_candid_record_n37(_uploadFile, _downloadFile, value);
}
function from_candid_StaffAttendance_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StaffAttendance): StaffAttendance {
    return from_candid_record_n42(_uploadFile, _downloadFile, value);
}
function from_candid_Treatment_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Treatment): Treatment {
    return from_candid_record_n53(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n59(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n62(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Location]): Location | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TreatmentPlan]): TreatmentPlan | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n58(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    spendings: Array<_Spending>;
    attendances: Array<_StaffAttendance>;
    staff: Array<_StaffMember>;
    sessions: Array<_PatientSession>;
    timestamp: _Time;
    patients: Array<_Patient>;
    miscExpenses: Array<_MiscExpense>;
}): {
    spendings: Array<Spending>;
    attendances: Array<StaffAttendance>;
    staff: Array<StaffMember>;
    sessions: Array<PatientSession>;
    timestamp: Time;
    patients: Array<Patient>;
    miscExpenses: Array<MiscExpense>;
} {
    return {
        spendings: from_candid_vec_n35(_uploadFile, _downloadFile, value.spendings),
        attendances: from_candid_vec_n40(_uploadFile, _downloadFile, value.attendances),
        staff: value.staff,
        sessions: from_candid_vec_n45(_uploadFile, _downloadFile, value.sessions),
        timestamp: value.timestamp,
        patients: from_candid_vec_n48(_uploadFile, _downloadFile, value.patients),
        miscExpenses: from_candid_vec_n55(_uploadFile, _downloadFile, value.miscExpenses)
    };
}
function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    date: _Time;
    description: string;
    category: _SpendingCategory;
    amount: bigint;
}): {
    id: string;
    date: Time;
    description: string;
    category: SpendingCategory;
    amount: bigint;
} {
    return {
        id: value.id,
        date: value.date,
        description: value.description,
        category: from_candid_SpendingCategory_n38(_uploadFile, _downloadFile, value.category),
        amount: value.amount
    };
}
function from_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    staffId: string;
    date: _Time;
    hoursWorked: bigint;
    clockOut: [] | [_Time];
    clockIn: _Time;
    totalPay: bigint;
    locationHistory: Array<_Location>;
    payRate: bigint;
    location: [] | [_Location];
}): {
    id: string;
    staffId: string;
    date: Time;
    hoursWorked: bigint;
    clockOut?: Time;
    clockIn: Time;
    totalPay: bigint;
    locationHistory: Array<Location>;
    payRate: bigint;
    location?: Location;
} {
    return {
        id: value.id,
        staffId: value.staffId,
        date: value.date,
        hoursWorked: value.hoursWorked,
        clockOut: record_opt_to_undefined(from_candid_opt_n43(_uploadFile, _downloadFile, value.clockOut)),
        clockIn: value.clockIn,
        totalPay: value.totalPay,
        locationHistory: value.locationHistory,
        payRate: value.payRate,
        location: record_opt_to_undefined(from_candid_opt_n44(_uploadFile, _downloadFile, value.location))
    };
}
function from_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    checkIn: _Time;
    duration: bigint;
    visitNumber: bigint;
    progressPercentage: bigint;
    patientId: string;
    date: _Time;
    treatmentPackageId: string;
    checkOut: [] | [_Time];
}): {
    id: string;
    checkIn: Time;
    duration: bigint;
    visitNumber: bigint;
    progressPercentage: bigint;
    patientId: string;
    date: Time;
    treatmentPackageId: string;
    checkOut?: Time;
} {
    return {
        id: value.id,
        checkIn: value.checkIn,
        duration: value.duration,
        visitNumber: value.visitNumber,
        progressPercentage: value.progressPercentage,
        patientId: value.patientId,
        date: value.date,
        treatmentPackageId: value.treatmentPackageId,
        checkOut: record_opt_to_undefined(from_candid_opt_n43(_uploadFile, _downloadFile, value.checkOut))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    debt: bigint;
    name: string;
    paid: bigint;
    diagnosis: string;
    address: string;
    phone: string;
    treatments: Array<_Treatment>;
}): {
    id: string;
    debt: bigint;
    name: string;
    paid: bigint;
    diagnosis: string;
    address: string;
    phone: string;
    treatments: Array<Treatment>;
} {
    return {
        id: value.id,
        debt: value.debt,
        name: value.name,
        paid: value.paid,
        diagnosis: value.diagnosis,
        address: value.address,
        phone: value.phone,
        treatments: from_candid_vec_n51(_uploadFile, _downloadFile, value.treatments)
    };
}
function from_candid_record_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    date: _Time;
    plan: [] | [_TreatmentPlan];
    type: string;
    notes: string;
    price: bigint;
}): {
    date: Time;
    plan?: TreatmentPlan;
    type: string;
    notes: string;
    price: bigint;
} {
    return {
        date: value.date,
        plan: record_opt_to_undefined(from_candid_opt_n54(_uploadFile, _downloadFile, value.plan)),
        type: value.type,
        notes: value.notes,
        price: value.price
    };
}
function from_candid_record_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    staffId: [] | [string];
    name: string;
    role: string;
}): {
    staffId?: string;
    name: string;
    role: string;
} {
    return {
        staffId: record_opt_to_undefined(from_candid_opt_n60(_uploadFile, _downloadFile, value.staffId)),
        name: value.name,
        role: value.role
    };
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    equipment: null;
} | {
    marketing: null;
} | {
    supplies: null;
} | {
    misc: null;
} | {
    rent: null;
} | {
    utilities: null;
} | {
    insurance: null;
} | {
    medications: null;
}): SpendingCategory {
    return "equipment" in value ? SpendingCategory.equipment : "marketing" in value ? SpendingCategory.marketing : "supplies" in value ? SpendingCategory.supplies : "misc" in value ? SpendingCategory.misc : "rent" in value ? SpendingCategory.rent : "utilities" in value ? SpendingCategory.utilities : "insurance" in value ? SpendingCategory.insurance : "medications" in value ? SpendingCategory.medications : value;
}
function from_candid_variant_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Spending>): Array<Spending> {
    return value.map((x)=>from_candid_Spending_n36(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StaffAttendance>): Array<StaffAttendance> {
    return value.map((x)=>from_candid_StaffAttendance_n41(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PatientSession>): Array<PatientSession> {
    return value.map((x)=>from_candid_PatientSession_n46(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Patient>): Array<Patient> {
    return value.map((x)=>from_candid_Patient_n49(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Treatment>): Array<Treatment> {
    return value.map((x)=>from_candid_Treatment_n52(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MiscExpense>): Array<MiscExpense> {
    return value.map((x)=>from_candid_MiscExpense_n56(_uploadFile, _downloadFile, x));
}
function to_candid_BackupData_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BackupData): _BackupData {
    return to_candid_record_n23(_uploadFile, _downloadFile, value);
}
function to_candid_ClockInData_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ClockInData): _ClockInData {
    return to_candid_record_n21(_uploadFile, _downloadFile, value);
}
function to_candid_EditableSessionFields_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EditableSessionFields): _EditableSessionFields {
    return to_candid_record_n66(_uploadFile, _downloadFile, value);
}
function to_candid_MiscExpense_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MiscExpense): _MiscExpense {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_PatientSession_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PatientSession): _PatientSession {
    return to_candid_record_n30(_uploadFile, _downloadFile, value);
}
function to_candid_Patient_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Patient): _Patient {
    return to_candid_record_n13(_uploadFile, _downloadFile, value);
}
function to_candid_SpendingCategory_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SpendingCategory): _SpendingCategory {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_Spending_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Spending): _Spending {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_StaffAttendance_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StaffAttendance): _StaffAttendance {
    return to_candid_record_n27(_uploadFile, _downloadFile, value);
}
function to_candid_Treatment_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Treatment): _Treatment {
    return to_candid_record_n16(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n64(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    debt: bigint;
    name: string;
    paid: bigint;
    diagnosis: string;
    address: string;
    phone: string;
    treatments: Array<Treatment>;
}): {
    id: string;
    debt: bigint;
    name: string;
    paid: bigint;
    diagnosis: string;
    address: string;
    phone: string;
    treatments: Array<_Treatment>;
} {
    return {
        id: value.id,
        debt: value.debt,
        name: value.name,
        paid: value.paid,
        diagnosis: value.diagnosis,
        address: value.address,
        phone: value.phone,
        treatments: to_candid_vec_n14(_uploadFile, _downloadFile, value.treatments)
    };
}
function to_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    date: Time;
    plan?: TreatmentPlan;
    type: string;
    notes: string;
    price: bigint;
}): {
    date: _Time;
    plan: [] | [_TreatmentPlan];
    type: string;
    notes: string;
    price: bigint;
} {
    return {
        date: value.date,
        plan: value.plan ? candid_some(value.plan) : candid_none(),
        type: value.type,
        notes: value.notes,
        price: value.price
    };
}
function to_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    staffId: string;
    location?: Location;
}): {
    staffId: string;
    location: [] | [_Location];
} {
    return {
        staffId: value.staffId,
        location: value.location ? candid_some(value.location) : candid_none()
    };
}
function to_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    spendings: Array<Spending>;
    attendances: Array<StaffAttendance>;
    staff: Array<StaffMember>;
    sessions: Array<PatientSession>;
    timestamp: Time;
    patients: Array<Patient>;
    miscExpenses: Array<MiscExpense>;
}): {
    spendings: Array<_Spending>;
    attendances: Array<_StaffAttendance>;
    staff: Array<_StaffMember>;
    sessions: Array<_PatientSession>;
    timestamp: _Time;
    patients: Array<_Patient>;
    miscExpenses: Array<_MiscExpense>;
} {
    return {
        spendings: to_candid_vec_n24(_uploadFile, _downloadFile, value.spendings),
        attendances: to_candid_vec_n25(_uploadFile, _downloadFile, value.attendances),
        staff: value.staff,
        sessions: to_candid_vec_n28(_uploadFile, _downloadFile, value.sessions),
        timestamp: value.timestamp,
        patients: to_candid_vec_n31(_uploadFile, _downloadFile, value.patients),
        miscExpenses: to_candid_vec_n32(_uploadFile, _downloadFile, value.miscExpenses)
    };
}
function to_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    staffId: string;
    date: Time;
    hoursWorked: bigint;
    clockOut?: Time;
    clockIn: Time;
    totalPay: bigint;
    locationHistory: Array<Location>;
    payRate: bigint;
    location?: Location;
}): {
    id: string;
    staffId: string;
    date: _Time;
    hoursWorked: bigint;
    clockOut: [] | [_Time];
    clockIn: _Time;
    totalPay: bigint;
    locationHistory: Array<_Location>;
    payRate: bigint;
    location: [] | [_Location];
} {
    return {
        id: value.id,
        staffId: value.staffId,
        date: value.date,
        hoursWorked: value.hoursWorked,
        clockOut: value.clockOut ? candid_some(value.clockOut) : candid_none(),
        clockIn: value.clockIn,
        totalPay: value.totalPay,
        locationHistory: value.locationHistory,
        payRate: value.payRate,
        location: value.location ? candid_some(value.location) : candid_none()
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    checkIn: Time;
    duration: bigint;
    visitNumber: bigint;
    progressPercentage: bigint;
    patientId: string;
    date: Time;
    treatmentPackageId: string;
    checkOut?: Time;
}): {
    id: string;
    checkIn: _Time;
    duration: bigint;
    visitNumber: bigint;
    progressPercentage: bigint;
    patientId: string;
    date: _Time;
    treatmentPackageId: string;
    checkOut: [] | [_Time];
} {
    return {
        id: value.id,
        checkIn: value.checkIn,
        duration: value.duration,
        visitNumber: value.visitNumber,
        progressPercentage: value.progressPercentage,
        patientId: value.patientId,
        date: value.date,
        treatmentPackageId: value.treatmentPackageId,
        checkOut: value.checkOut ? candid_some(value.checkOut) : candid_none()
    };
}
function to_candid_record_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    staffId?: string;
    name: string;
    role: string;
}): {
    staffId: [] | [string];
    name: string;
    role: string;
} {
    return {
        staffId: value.staffId ? candid_some(value.staffId) : candid_none(),
        name: value.name,
        role: value.role
    };
}
function to_candid_record_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    checkIn?: Time;
    duration?: bigint;
    visitNumber?: bigint;
    progressPercentage?: bigint;
    patientId?: string;
    date?: Time;
    treatmentPackageId?: string;
    checkOut?: Time;
}): {
    checkIn: [] | [_Time];
    duration: [] | [bigint];
    visitNumber: [] | [bigint];
    progressPercentage: [] | [bigint];
    patientId: [] | [string];
    date: [] | [_Time];
    treatmentPackageId: [] | [string];
    checkOut: [] | [_Time];
} {
    return {
        checkIn: value.checkIn ? candid_some(value.checkIn) : candid_none(),
        duration: value.duration ? candid_some(value.duration) : candid_none(),
        visitNumber: value.visitNumber ? candid_some(value.visitNumber) : candid_none(),
        progressPercentage: value.progressPercentage ? candid_some(value.progressPercentage) : candid_none(),
        patientId: value.patientId ? candid_some(value.patientId) : candid_none(),
        date: value.date ? candid_some(value.date) : candid_none(),
        treatmentPackageId: value.treatmentPackageId ? candid_some(value.treatmentPackageId) : candid_none(),
        checkOut: value.checkOut ? candid_some(value.checkOut) : candid_none()
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    date: Time;
    description: string;
    category: SpendingCategory;
    amount: bigint;
}): {
    id: string;
    date: _Time;
    description: string;
    category: _SpendingCategory;
    amount: bigint;
} {
    return {
        id: value.id,
        date: value.date,
        description: value.description,
        category: to_candid_SpendingCategory_n10(_uploadFile, _downloadFile, value.category),
        amount: value.amount
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SpendingCategory): {
    equipment: null;
} | {
    marketing: null;
} | {
    supplies: null;
} | {
    misc: null;
} | {
    rent: null;
} | {
    utilities: null;
} | {
    insurance: null;
} | {
    medications: null;
} {
    return value == SpendingCategory.equipment ? {
        equipment: null
    } : value == SpendingCategory.marketing ? {
        marketing: null
    } : value == SpendingCategory.supplies ? {
        supplies: null
    } : value == SpendingCategory.misc ? {
        misc: null
    } : value == SpendingCategory.rent ? {
        rent: null
    } : value == SpendingCategory.utilities ? {
        utilities: null
    } : value == SpendingCategory.insurance ? {
        insurance: null
    } : value == SpendingCategory.medications ? {
        medications: null
    } : value;
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Treatment>): Array<_Treatment> {
    return value.map((x)=>to_candid_Treatment_n15(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Spending>): Array<_Spending> {
    return value.map((x)=>to_candid_Spending_n17(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<StaffAttendance>): Array<_StaffAttendance> {
    return value.map((x)=>to_candid_StaffAttendance_n26(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<PatientSession>): Array<_PatientSession> {
    return value.map((x)=>to_candid_PatientSession_n29(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Patient>): Array<_Patient> {
    return value.map((x)=>to_candid_Patient_n12(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<MiscExpense>): Array<_MiscExpense> {
    return value.map((x)=>to_candid_MiscExpense_n8(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
