/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Time = IDL.Int;
export const SpendingCategory = IDL.Variant({
  'equipment' : IDL.Null,
  'marketing' : IDL.Null,
  'supplies' : IDL.Null,
  'misc' : IDL.Null,
  'rent' : IDL.Null,
  'utilities' : IDL.Null,
  'insurance' : IDL.Null,
  'medications' : IDL.Null,
});
export const MiscExpense = IDL.Record({
  'id' : IDL.Text,
  'date' : Time,
  'description' : IDL.Text,
  'category' : SpendingCategory,
  'amount' : IDL.Nat,
});
export const TreatmentPlan = IDL.Record({
  'endDate' : Time,
  'description' : IDL.Text,
  'startDate' : Time,
});
export const Treatment = IDL.Record({
  'date' : Time,
  'plan' : IDL.Opt(TreatmentPlan),
  'type' : IDL.Text,
  'notes' : IDL.Text,
  'price' : IDL.Nat,
});
export const Patient = IDL.Record({
  'id' : IDL.Text,
  'debt' : IDL.Nat,
  'name' : IDL.Text,
  'paid' : IDL.Nat,
  'diagnosis' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
  'treatments' : IDL.Vec(Treatment),
});
export const Spending = IDL.Record({
  'id' : IDL.Text,
  'date' : Time,
  'description' : IDL.Text,
  'category' : SpendingCategory,
  'amount' : IDL.Nat,
});
export const StaffMember = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'qualifications' : IDL.Text,
  'phone' : IDL.Text,
  'position' : IDL.Text,
  'payRate' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CheckInData = IDL.Record({
  'visitNumber' : IDL.Nat,
  'patientId' : IDL.Text,
  'treatmentPackageId' : IDL.Text,
});
export const CheckOutData = IDL.Record({ 'patientId' : IDL.Text });
export const Location = IDL.Record({
  'latitude' : IDL.Float64,
  'longitude' : IDL.Float64,
  'timestamp' : Time,
});
export const ClockInData = IDL.Record({
  'staffId' : IDL.Text,
  'location' : IDL.Opt(Location),
});
export const ClockOutData = IDL.Record({ 'staffId' : IDL.Text });
export const StaffAttendance = IDL.Record({
  'id' : IDL.Text,
  'staffId' : IDL.Text,
  'date' : Time,
  'hoursWorked' : IDL.Nat,
  'clockOut' : IDL.Opt(Time),
  'clockIn' : Time,
  'totalPay' : IDL.Nat,
  'locationHistory' : IDL.Vec(Location),
  'payRate' : IDL.Nat,
  'location' : IDL.Opt(Location),
});
export const PatientSession = IDL.Record({
  'id' : IDL.Text,
  'checkIn' : Time,
  'duration' : IDL.Nat,
  'visitNumber' : IDL.Nat,
  'progressPercentage' : IDL.Nat,
  'patientId' : IDL.Text,
  'date' : Time,
  'treatmentPackageId' : IDL.Text,
  'checkOut' : IDL.Opt(Time),
});
export const BackupData = IDL.Record({
  'spendings' : IDL.Vec(Spending),
  'attendances' : IDL.Vec(StaffAttendance),
  'staff' : IDL.Vec(StaffMember),
  'sessions' : IDL.Vec(PatientSession),
  'timestamp' : Time,
  'patients' : IDL.Vec(Patient),
  'miscExpenses' : IDL.Vec(MiscExpense),
});
export const BackupRecord = IDL.Record({
  'id' : IDL.Text,
  'timestamp' : Time,
  'recordCount' : IDL.Record({
    'spendings' : IDL.Nat,
    'attendances' : IDL.Nat,
    'staff' : IDL.Nat,
    'sessions' : IDL.Nat,
    'patients' : IDL.Nat,
    'miscExpenses' : IDL.Nat,
  }),
});
export const UserProfile = IDL.Record({
  'staffId' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'role' : IDL.Text,
});
export const EditableSessionFields = IDL.Record({
  'checkIn' : IDL.Opt(Time),
  'duration' : IDL.Opt(IDL.Nat),
  'visitNumber' : IDL.Opt(IDL.Nat),
  'progressPercentage' : IDL.Opt(IDL.Nat),
  'patientId' : IDL.Opt(IDL.Text),
  'date' : IDL.Opt(Time),
  'treatmentPackageId' : IDL.Opt(IDL.Text),
  'checkOut' : IDL.Opt(Time),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addMiscExpense' : IDL.Func([MiscExpense], [], []),
  'addPatient' : IDL.Func([Patient], [], []),
  'addSpending' : IDL.Func([Spending], [], []),
  'addStaff' : IDL.Func([StaffMember], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkInPatient' : IDL.Func([CheckInData], [], []),
  'checkOutPatient' : IDL.Func([CheckOutData], [], []),
  'clockInStaff' : IDL.Func([ClockInData], [], []),
  'clockOutStaff' : IDL.Func([ClockOutData], [], []),
  'createBackupRecord' : IDL.Func([BackupData, IDL.Text], [], []),
  'deleteMiscExpense' : IDL.Func([IDL.Text], [], []),
  'deletePatient' : IDL.Func([IDL.Text], [], []),
  'deleteStaff' : IDL.Func([IDL.Text], [], []),
  'editCheckInTime' : IDL.Func([IDL.Text, IDL.Text, Time], [], []),
  'editCheckOutTime' : IDL.Func([IDL.Text, IDL.Text, Time], [], []),
  'editClockInTime' : IDL.Func([IDL.Text, IDL.Text, Time], [], []),
  'editClockOutTime' : IDL.Func([IDL.Text, IDL.Text, Time], [], []),
  'editSpending' : IDL.Func([IDL.Text, Spending], [], []),
  'exportAllData' : IDL.Func([], [BackupData], ['query']),
  'getAllAttendances' : IDL.Func([], [IDL.Vec(StaffAttendance)], ['query']),
  'getAllMiscExpenses' : IDL.Func([], [IDL.Vec(MiscExpense)], ['query']),
  'getAllPatients' : IDL.Func([], [IDL.Vec(Patient)], ['query']),
  'getAllSessions' : IDL.Func([], [IDL.Vec(PatientSession)], ['query']),
  'getAllSpendings' : IDL.Func([], [IDL.Vec(Spending)], ['query']),
  'getAllStaff' : IDL.Func([], [IDL.Vec(StaffMember)], ['query']),
  'getBackupRecords' : IDL.Func([], [IDL.Vec(BackupRecord)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPatientSessions' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(PatientSession)],
      ['query'],
    ),
  'getSpendingsByCategory' : IDL.Func(
      [SpendingCategory],
      [IDL.Vec(Spending)],
      ['query'],
    ),
  'getStaffAttendance' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(StaffAttendance)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'importBackupData' : IDL.Func([BackupData], [], []),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'mergeBackupData' : IDL.Func([BackupData], [], []),
  'resetAllData' : IDL.Func([], [], []),
  'resetAllPatients' : IDL.Func([], [], []),
  'resetAllStaff' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateMiscExpense' : IDL.Func([IDL.Text, MiscExpense], [], []),
  'updatePatient' : IDL.Func([IDL.Text, Patient], [], []),
  'updatePatientSession' : IDL.Func([IDL.Text, EditableSessionFields], [], []),
  'updateStaff' : IDL.Func([IDL.Text, StaffMember], [], []),
  'updateStaffLocation' : IDL.Func([IDL.Text, Location], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Time = IDL.Int;
  const SpendingCategory = IDL.Variant({
    'equipment' : IDL.Null,
    'marketing' : IDL.Null,
    'supplies' : IDL.Null,
    'misc' : IDL.Null,
    'rent' : IDL.Null,
    'utilities' : IDL.Null,
    'insurance' : IDL.Null,
    'medications' : IDL.Null,
  });
  const MiscExpense = IDL.Record({
    'id' : IDL.Text,
    'date' : Time,
    'description' : IDL.Text,
    'category' : SpendingCategory,
    'amount' : IDL.Nat,
  });
  const TreatmentPlan = IDL.Record({
    'endDate' : Time,
    'description' : IDL.Text,
    'startDate' : Time,
  });
  const Treatment = IDL.Record({
    'date' : Time,
    'plan' : IDL.Opt(TreatmentPlan),
    'type' : IDL.Text,
    'notes' : IDL.Text,
    'price' : IDL.Nat,
  });
  const Patient = IDL.Record({
    'id' : IDL.Text,
    'debt' : IDL.Nat,
    'name' : IDL.Text,
    'paid' : IDL.Nat,
    'diagnosis' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
    'treatments' : IDL.Vec(Treatment),
  });
  const Spending = IDL.Record({
    'id' : IDL.Text,
    'date' : Time,
    'description' : IDL.Text,
    'category' : SpendingCategory,
    'amount' : IDL.Nat,
  });
  const StaffMember = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'qualifications' : IDL.Text,
    'phone' : IDL.Text,
    'position' : IDL.Text,
    'payRate' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CheckInData = IDL.Record({
    'visitNumber' : IDL.Nat,
    'patientId' : IDL.Text,
    'treatmentPackageId' : IDL.Text,
  });
  const CheckOutData = IDL.Record({ 'patientId' : IDL.Text });
  const Location = IDL.Record({
    'latitude' : IDL.Float64,
    'longitude' : IDL.Float64,
    'timestamp' : Time,
  });
  const ClockInData = IDL.Record({
    'staffId' : IDL.Text,
    'location' : IDL.Opt(Location),
  });
  const ClockOutData = IDL.Record({ 'staffId' : IDL.Text });
  const StaffAttendance = IDL.Record({
    'id' : IDL.Text,
    'staffId' : IDL.Text,
    'date' : Time,
    'hoursWorked' : IDL.Nat,
    'clockOut' : IDL.Opt(Time),
    'clockIn' : Time,
    'totalPay' : IDL.Nat,
    'locationHistory' : IDL.Vec(Location),
    'payRate' : IDL.Nat,
    'location' : IDL.Opt(Location),
  });
  const PatientSession = IDL.Record({
    'id' : IDL.Text,
    'checkIn' : Time,
    'duration' : IDL.Nat,
    'visitNumber' : IDL.Nat,
    'progressPercentage' : IDL.Nat,
    'patientId' : IDL.Text,
    'date' : Time,
    'treatmentPackageId' : IDL.Text,
    'checkOut' : IDL.Opt(Time),
  });
  const BackupData = IDL.Record({
    'spendings' : IDL.Vec(Spending),
    'attendances' : IDL.Vec(StaffAttendance),
    'staff' : IDL.Vec(StaffMember),
    'sessions' : IDL.Vec(PatientSession),
    'timestamp' : Time,
    'patients' : IDL.Vec(Patient),
    'miscExpenses' : IDL.Vec(MiscExpense),
  });
  const BackupRecord = IDL.Record({
    'id' : IDL.Text,
    'timestamp' : Time,
    'recordCount' : IDL.Record({
      'spendings' : IDL.Nat,
      'attendances' : IDL.Nat,
      'staff' : IDL.Nat,
      'sessions' : IDL.Nat,
      'patients' : IDL.Nat,
      'miscExpenses' : IDL.Nat,
    }),
  });
  const UserProfile = IDL.Record({
    'staffId' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'role' : IDL.Text,
  });
  const EditableSessionFields = IDL.Record({
    'checkIn' : IDL.Opt(Time),
    'duration' : IDL.Opt(IDL.Nat),
    'visitNumber' : IDL.Opt(IDL.Nat),
    'progressPercentage' : IDL.Opt(IDL.Nat),
    'patientId' : IDL.Opt(IDL.Text),
    'date' : IDL.Opt(Time),
    'treatmentPackageId' : IDL.Opt(IDL.Text),
    'checkOut' : IDL.Opt(Time),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addMiscExpense' : IDL.Func([MiscExpense], [], []),
    'addPatient' : IDL.Func([Patient], [], []),
    'addSpending' : IDL.Func([Spending], [], []),
    'addStaff' : IDL.Func([StaffMember], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkInPatient' : IDL.Func([CheckInData], [], []),
    'checkOutPatient' : IDL.Func([CheckOutData], [], []),
    'clockInStaff' : IDL.Func([ClockInData], [], []),
    'clockOutStaff' : IDL.Func([ClockOutData], [], []),
    'createBackupRecord' : IDL.Func([BackupData, IDL.Text], [], []),
    'deleteMiscExpense' : IDL.Func([IDL.Text], [], []),
    'deletePatient' : IDL.Func([IDL.Text], [], []),
    'deleteStaff' : IDL.Func([IDL.Text], [], []),
    'editCheckInTime' : IDL.Func([IDL.Text, IDL.Text, Time], [], []),
    'editCheckOutTime' : IDL.Func([IDL.Text, IDL.Text, Time], [], []),
    'editClockInTime' : IDL.Func([IDL.Text, IDL.Text, Time], [], []),
    'editClockOutTime' : IDL.Func([IDL.Text, IDL.Text, Time], [], []),
    'editSpending' : IDL.Func([IDL.Text, Spending], [], []),
    'exportAllData' : IDL.Func([], [BackupData], ['query']),
    'getAllAttendances' : IDL.Func([], [IDL.Vec(StaffAttendance)], ['query']),
    'getAllMiscExpenses' : IDL.Func([], [IDL.Vec(MiscExpense)], ['query']),
    'getAllPatients' : IDL.Func([], [IDL.Vec(Patient)], ['query']),
    'getAllSessions' : IDL.Func([], [IDL.Vec(PatientSession)], ['query']),
    'getAllSpendings' : IDL.Func([], [IDL.Vec(Spending)], ['query']),
    'getAllStaff' : IDL.Func([], [IDL.Vec(StaffMember)], ['query']),
    'getBackupRecords' : IDL.Func([], [IDL.Vec(BackupRecord)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPatientSessions' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PatientSession)],
        ['query'],
      ),
    'getSpendingsByCategory' : IDL.Func(
        [SpendingCategory],
        [IDL.Vec(Spending)],
        ['query'],
      ),
    'getStaffAttendance' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(StaffAttendance)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'importBackupData' : IDL.Func([BackupData], [], []),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'mergeBackupData' : IDL.Func([BackupData], [], []),
    'resetAllData' : IDL.Func([], [], []),
    'resetAllPatients' : IDL.Func([], [], []),
    'resetAllStaff' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateMiscExpense' : IDL.Func([IDL.Text, MiscExpense], [], []),
    'updatePatient' : IDL.Func([IDL.Text, Patient], [], []),
    'updatePatientSession' : IDL.Func(
        [IDL.Text, EditableSessionFields],
        [],
        [],
      ),
    'updateStaff' : IDL.Func([IDL.Text, StaffMember], [], []),
    'updateStaffLocation' : IDL.Func([IDL.Text, Location], [], []),
  });
};

export const init = ({ IDL }) => { return []; };