/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BackupData {
  'spendings' : Array<Spending>,
  'attendances' : Array<StaffAttendance>,
  'staff' : Array<StaffMember>,
  'sessions' : Array<PatientSession>,
  'timestamp' : Time,
  'patients' : Array<Patient>,
  'miscExpenses' : Array<MiscExpense>,
}
export interface BackupRecord {
  'id' : string,
  'timestamp' : Time,
  'recordCount' : {
    'spendings' : bigint,
    'attendances' : bigint,
    'staff' : bigint,
    'sessions' : bigint,
    'patients' : bigint,
    'miscExpenses' : bigint,
  },
}
export interface CheckInData {
  'visitNumber' : bigint,
  'patientId' : string,
  'treatmentPackageId' : string,
}
export interface CheckOutData { 'patientId' : string }
export interface ClockInData {
  'staffId' : string,
  'location' : [] | [Location],
}
export interface ClockOutData { 'staffId' : string }
export interface EditableSessionFields {
  'checkIn' : [] | [Time],
  'duration' : [] | [bigint],
  'visitNumber' : [] | [bigint],
  'progressPercentage' : [] | [bigint],
  'patientId' : [] | [string],
  'date' : [] | [Time],
  'treatmentPackageId' : [] | [string],
  'checkOut' : [] | [Time],
}
export interface Location {
  'latitude' : number,
  'longitude' : number,
  'timestamp' : Time,
}
export interface MiscExpense {
  'id' : string,
  'date' : Time,
  'description' : string,
  'category' : SpendingCategory,
  'amount' : bigint,
}
export interface Patient {
  'id' : string,
  'debt' : bigint,
  'name' : string,
  'paid' : bigint,
  'diagnosis' : string,
  'address' : string,
  'phone' : string,
  'treatments' : Array<Treatment>,
}
export interface PatientSession {
  'id' : string,
  'checkIn' : Time,
  'duration' : bigint,
  'visitNumber' : bigint,
  'progressPercentage' : bigint,
  'patientId' : string,
  'date' : Time,
  'treatmentPackageId' : string,
  'checkOut' : [] | [Time],
}
export interface Spending {
  'id' : string,
  'date' : Time,
  'description' : string,
  'category' : SpendingCategory,
  'amount' : bigint,
}
export type SpendingCategory = { 'equipment' : null } |
  { 'marketing' : null } |
  { 'supplies' : null } |
  { 'misc' : null } |
  { 'rent' : null } |
  { 'utilities' : null } |
  { 'insurance' : null } |
  { 'medications' : null };
export interface StaffAttendance {
  'id' : string,
  'staffId' : string,
  'date' : Time,
  'hoursWorked' : bigint,
  'clockOut' : [] | [Time],
  'clockIn' : Time,
  'totalPay' : bigint,
  'locationHistory' : Array<Location>,
  'payRate' : bigint,
  'location' : [] | [Location],
}
export interface StaffMember {
  'id' : string,
  'name' : string,
  'qualifications' : string,
  'phone' : string,
  'position' : string,
  'payRate' : bigint,
}
export type Time = bigint;
export interface Treatment {
  'date' : Time,
  'plan' : [] | [TreatmentPlan],
  'type' : string,
  'notes' : string,
  'price' : bigint,
}
export interface TreatmentPlan {
  'endDate' : Time,
  'description' : string,
  'startDate' : Time,
}
export interface UserProfile {
  'staffId' : [] | [string],
  'name' : string,
  'role' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addMiscExpense' : ActorMethod<[MiscExpense], undefined>,
  'addPatient' : ActorMethod<[Patient], undefined>,
  'addSpending' : ActorMethod<[Spending], undefined>,
  'addStaff' : ActorMethod<[StaffMember], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkInPatient' : ActorMethod<[CheckInData], undefined>,
  'checkOutPatient' : ActorMethod<[CheckOutData], undefined>,
  'clockInStaff' : ActorMethod<[ClockInData], undefined>,
  'clockOutStaff' : ActorMethod<[ClockOutData], undefined>,
  'createBackupRecord' : ActorMethod<[BackupData, string], undefined>,
  'deleteMiscExpense' : ActorMethod<[string], undefined>,
  'deletePatient' : ActorMethod<[string], undefined>,
  'deleteStaff' : ActorMethod<[string], undefined>,
  'editCheckInTime' : ActorMethod<[string, string, Time], undefined>,
  'editCheckOutTime' : ActorMethod<[string, string, Time], undefined>,
  'editClockInTime' : ActorMethod<[string, string, Time], undefined>,
  'editClockOutTime' : ActorMethod<[string, string, Time], undefined>,
  'editSpending' : ActorMethod<[string, Spending], undefined>,
  'exportAllData' : ActorMethod<[], BackupData>,
  'getAllAttendances' : ActorMethod<[], Array<StaffAttendance>>,
  'getAllMiscExpenses' : ActorMethod<[], Array<MiscExpense>>,
  'getAllPatients' : ActorMethod<[], Array<Patient>>,
  'getAllSessions' : ActorMethod<[], Array<PatientSession>>,
  'getAllSpendings' : ActorMethod<[], Array<Spending>>,
  'getAllStaff' : ActorMethod<[], Array<StaffMember>>,
  'getBackupRecords' : ActorMethod<[], Array<BackupRecord>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPatientSessions' : ActorMethod<[string], Array<PatientSession>>,
  'getSpendingsByCategory' : ActorMethod<[SpendingCategory], Array<Spending>>,
  'getStaffAttendance' : ActorMethod<[string], Array<StaffAttendance>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'importBackupData' : ActorMethod<[BackupData], undefined>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'mergeBackupData' : ActorMethod<[BackupData], undefined>,
  'resetAllData' : ActorMethod<[], undefined>,
  'resetAllPatients' : ActorMethod<[], undefined>,
  'resetAllStaff' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateMiscExpense' : ActorMethod<[string, MiscExpense], undefined>,
  'updatePatient' : ActorMethod<[string, Patient], undefined>,
  'updatePatientSession' : ActorMethod<
    [string, EditableSessionFields],
    undefined
  >,
  'updateStaff' : ActorMethod<[string, StaffMember], undefined>,
  'updateStaffLocation' : ActorMethod<[string, Location], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];